# Playbook that updates the current instance

- hosts: localhost
  vars:
    # Required to use docker_compose properly
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
      - ".vars.yml"
  tasks:
    - name: Pull Changes
      shell: git pull
      args:
        chdir: /home/viame

    - name: Build Service
      ignore_errors: yes
      register: build
      docker_compose:
        project_src: /home/viame/docker
        build: yes
        state: present

    - name: Send email on build failure
      ignore_errors: yes
      when: build.failed
      mail:
        from: "{{ deploy_email_address }}"
        to: "{{ notify_email_address  }}"
        subject: Failed Build of Viame-Web
        body: |
          Captured stdout:
          {{ build.module_stdout  }}

          Captured stderr:
          {{ build.module_stderr  }}

    - name: Stop Service
      when: not build.failed
      docker_compose:
        project_src: /home/viame
        state: absent

    - name: Start Service
      docker_compose:
        project_src: /home/viame
        state: absent
