## Use this to start the girder/ girder-worker ecosystem
version: "3.2"
services:
  ## === === === === prebuilt services === === === === ===
  rabbit:
    image: rabbitmq:management

  mongo:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  ## === === === === Building Base Images === === === === ===

  # Not sure if we need this
  # base_girder_worker:
  #   image: gitlab.kitware.com:4567/opengeoscience/viameweb/base/girder_worker

  ## === === === === Girder === === === === ===
  girder:
    build:
      context: ../
      dockerfile: docker/girder.Dockerfile
      args:
        - databaseURI=mongodb://mongo:27017/girder
    depends_on:
      - mongo
      - girder_worker
    ports:
      - "8081:${GIRDER_INNER_PORT}"
    volumes:
      - girder_assetstore:/home/assetstore
      - ./server:/home/viame_girder
      - pipelines:${/home/VIAME/pipelines}:ro
      - type: bind
        source: ${PUBLIC_DATA_PATH}
        target: /data/public
        read_only: true
        volume:
          nocopy: true
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
      - BROKER_URL=amqp://guest:guest@rabbit/
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit/
      - BROKER_CONNECTION_TIMEOUT=2
      - CELERY_BROKER_CONNECTION_TIMEOUT=2
      - GIRDER_INNER_PORT=${GIRDER_INNER_PORT}

  ## === === === === Girder Worker === === === === ===

  girder_worker:
    volumes:
      - ./server:/home/viame_girder
      - pipelines:/home/VIAME/build/install/configs/pipelines
    depends_on:
      - rabbit
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
      - BROKER_URL=amqp://guest:guest@rabbit/
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit/
      - BROKER_CONNECTION_TIMEOUT=2
      - CELERY_BROKER_CONNECTION_TIMEOUT=2
      - GIRDER_ADMIN_USER=${GIRDER_ADMIN_USER}
      - GIRDER_ADMIN_PASS=${GIRDER_ADMIN_PASS}
    # image: gitlab.kitware.com:4567/opengeoscience/viameweb/app/girder_worker
    # Replaced with build because girder.py changed
    build:
      context: ../
      dockerfile: docker/viame_girder_worker.Dockerfile

volumes:
  mongo_db:
  girder_assetstore:
  pipelines:
